"""config.yaml + cuts.json -> firmware/common/fleet_config.h"""

import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from orchestrator.config import load_config  # noqa: E402


def main():
    cfg = load_config()
    cuts_path = ROOT / cfg.model.artifacts_dir / "cuts.json"
    assert cuts_path.exists(), "cuts.json missing - run `make slice` first"
    cuts = json.loads(cuts_path.read_text())["cuts"]

    lines = [
        "// GENERATED by scripts/gen_config_header.py from config.yaml - do not edit",
        "#pragma once", "",
        f'#define FLEET_SSID "{cfg.network.ssid}"',
        f'#define FLEET_PSK "{cfg.network.wpa2_psk}"',
        f'#define FLEET_SERVER_IP "{cfg.network.server_ip}"',
        f"#define FLEET_PORT_CTRL {cfg.network.ports.control}",
        f"#define FLEET_PORT_DATA {cfg.network.ports.data}",
        f"#define FLEET_FRAG_PAYLOAD {cfg.network.fragment_payload_bytes}",
        f"#define FLEET_HEARTBEAT_MS {cfg.registry.heartbeat_period_s * 1000}",
        f"#define FLEET_JPEG_QUALITY {cfg.model.jpeg_quality}",
        f"#define FLEET_INPUT_SIZE {cfg.model.input_size}",
        f"#define FLEET_INPUT_BYTES {cfg.model.input_size * cfg.model.input_size * 3}",
        f"#define FLEET_FLASH_IMAGES {cfg.model.flash_image_count}",
        f"#define FLEET_N_CUTS {len(cfg.cuts)}", "",
    ]
    max_tensor = 0
    for i, cut in enumerate(cfg.cuts):
        lines.append(f"#define FLEET_CUT_{cut.name.upper()} {i}")
        if cut.boundary_op is not None:
            info = next(c for c in cuts if c["name"] == cut.name)
            lines.append(f"#define FLEET_TENSOR_BYTES_CUT{i} {info['tensor_bytes']}")
            max_tensor = max(max_tensor, info["tensor_bytes"])
    lines += ["", f"#define FLEET_MAX_TENSOR_BYTES {max_tensor}", "",
              "/* The orchestrator abandons a request after this; the device must not",
              "   stay busy any longer, or it misses the next ASSIGN. */",
              f"#define FLEET_T_MAX_MS {cfg.protocol.t_max_ms}", ""]

    out = ROOT / "firmware" / "common" / "fleet_config.h"
    out.write_text("\n".join(lines))
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
